name: futsta
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


flutter:
  assets:
    - .env
    - assets/club_logo.png

  uses-material-design: true


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  intl: ^0.18.0
  flutter_dotenv: ^5.0.2
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.0"
  flutter_lints: ^2.0.1

flutter_icons:
  image_path: "assets/launcher_icon.png"
  web:
    generate: true
    image_path: "assets/launcher_icon.png"